# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HKUtility' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  #基础宏定义，类别
  pod 'HKMacros', :git => 'https://gitee.com/Steven_Hu/HKMacros.git'
  #动画合集/过度动画
  pod 'HKTransitionTool', :git => 'https://gitee.com/Steven_Hu/HKTransitionTool.git'
  #异常捕获CrashCaught
  pod 'HKExceptionHandler', :git => 'https://gitee.com/Steven_Hu/HKExceptionHandler.git'
  #可复用强的弹窗，支持多种弹出样式，支持三种不同风格的Dialog
  pod 'HKAlertView', :git => 'https://gitee.com/Steven_Hu/HKAlertView.git'
  #HKMessageBox支持Toast提示，loading字样，HKToast还可支持设置位置Position
  pod 'HKMessageBox', :git => 'https://gitee.com/Steven_Hu/HKMessageBox.git'
  #HKSelectAlert传入数组字符串可展示选项框提供选择，支持纵向和竖向两种展示方式
  pod 'HKSelectAlert', :git => 'https://gitee.com/Steven_Hu/HKSelectAlert.git'
  #路由
  pod 'HKRouter', :git => 'https://gitee.com/Steven_Hu/HKRouter.git'
  
  #请求类
  pod 'AFNetworking', '~> 3.2.1'
  #自动布局
  pod 'Masonry'
  pod 'HandyFrame'
  #图片加载
  pod 'SDWebImage', '~> 5.0.0-beta3'
  # Pods for HKUtility
  
  target 'HKUtilityTests' do
    inherit! :search_paths
  end

  target 'HKUtilityUITests' do
    inherit! :search_paths
  end

end
